superlink-connection: "local-300"
max-experiment-duration-s: 28800 # 8 hours hard kill per experiment
experiments:
  # ====================== alpha = 2.0 ======================
  # ====================== seed = 42 ======================
  - {
      name: g1_oort_mnli_s42,
      bases: [pools/300, datasets/mnli, strategies/oort],
      overrides: ["seed=42", "wandb.run-name=a2-v5"],
    }

  # ====================== alpha = 0.5 ======================
  # ====================== seed = 42 ======================
  - {
      name: g1_oort_mnli_s42,
      bases: [pools/300, datasets/mnli, strategies/oort],
      overrides: ["seed=42", "wandb.run-name=a0.5-v5", "dataset.partition.dirichlet.alpha=0.5"],
    }

  # ====================== IID ======================
  # ====================== seed = 42 ======================
  - {
      name: g2_oort_mnli_iid_s42,
      bases: [pools/300, datasets/mnli, strategies/oort],
      overrides: ["seed=42", "wandb.run-name=iid-v5", "dataset.partition.strategy=iid"],
    }