description: >
  HotFix for Oort and TiFL in MNLI under different non-IID settings (alpha=2, alpha=0.5, and IID).

superlink-connection: "local-300"
max-experiment-duration-s: 28800
experiments:
  # ====================== seed = 42 ======================
  - {
      name: g2_tifl_mnli_a2_s42,
      bases: [pools/300, datasets/mnli, strategies/tifl, strategies/tifl_300],
      overrides: ["seed=42", "dataset.partition.dirichlet.alpha=2", "wandb.run-name=a2-v2"],
    }
  - {
      name: g2_oort_mnli_a2_s42,
      bases: [pools/300, datasets/mnli, strategies/oort, strategies/oort_300],
      overrides: ["seed=42", "dataset.partition.dirichlet.alpha=2", "wandb.run-name=a2-v2"],
    }

  # alpha = 0.5 (high non-IID)
  - {
      name: g2_tifl_mnli_a05_s42,
      bases: [pools/300, datasets/mnli, strategies/tifl, strategies/tifl_300],
      overrides: ["seed=42", "dataset.partition.dirichlet.alpha=0.5", "wandb.run-name=a0.5-v2"],
    }
  - {
      name: g2_oort_mnli_a05_s42,
      bases: [pools/300, datasets/mnli, strategies/oort, strategies/oort_300],
      overrides: ["seed=42", "dataset.partition.dirichlet.alpha=0.5", "wandb.run-name=a0.5-v2"],
    }

  # IID
  - {
      name: g2_tifl_mnli_iid_s42,
      bases: [pools/300, datasets/mnli, strategies/tifl, strategies/tifl_300],
      overrides: ["seed=42", "dataset.partition.strategy=iid", "wandb.run-name=iid-v2"],
    }
  - {
      name: g2_oort_mnli_iid_s42,
      bases: [pools/300, datasets/mnli, strategies/oort, strategies/oort_300],
      overrides: ["seed=42", "dataset.partition.strategy=iid", "wandb.run-name=iid-v2"],
    }
