description: >
  HotFix for Oort and TiFL in BoolQ
superlink-connection: "local-50"
experiments:
  # ====================== Mainly for alpha = 2 ===========
  # ====================== seed = 42 ======================
  - {
      name: a2_tifl_boolq_s42,
      bases: [pools/50, datasets/boolq, strategies/tifl, strategies/tifl_50],
      overrides: ["seed=42", "wandb.run-name=a2-v2"],
    }
  - {
      name: a2_oort_boolq_s42,
      bases: [pools/50, datasets/boolq, strategies/oort, strategies/oort_50],
      overrides: ["seed=42", "wandb.run-name=a2-v2"],
    }

  # ====================== seed = 123 ======================
  - {
      name: a2_tifl_boolq_s123,
      bases: [pools/50, datasets/boolq, strategies/tifl, strategies/tifl_50],
      overrides: ["seed=123", "wandb.run-name=a2-v2"],
    }
  - {
      name: a2_oort_boolq_s123,
      bases: [pools/50, datasets/boolq, strategies/oort, strategies/oort_50],
      overrides: ["seed=123", "wandb.run-name=a2-v2"],
    }

  # ====================== seed = 456 ======================
  - {
      name: a2_tifl_boolq_s456,
      bases: [pools/50, datasets/boolq, strategies/tifl, strategies/tifl_50],
      overrides: ["seed=456", "wandb.run-name=a2-v2"],
    }
  - {
      name: a2_oort_boolq_s456,
      bases: [pools/50, datasets/boolq, strategies/oort, strategies/oort_50],
      overrides: ["seed=456", "wandb.run-name=a2-v2"],
    }

  # Only for seed = 42
  # ====================== Alpha = 0.5 ===========
  - {
      name: a05_tifl_boolq_s42,
      bases: [pools/50, datasets/boolq, strategies/tifl, strategies/tifl_50],
      overrides: ["seed=42", "dataset.partition.dirichlet.alpha=0.5", "wandb.run-name=a0.5-v2"],
    }
  - {
      name: a05_oort_boolq_s42,
      bases: [pools/50, datasets/boolq, strategies/oort, strategies/oort_50],
      overrides: ["seed=42", "dataset.partition.dirichlet.alpha=0.5", "wandb.run-name=a0.5-v2"],
    }

    # ====================== IID ===========
  - {
      name: iid_tifl_boolq_s42,
      bases: [pools/50, datasets/boolq, strategies/tifl, strategies/tifl_50],
      overrides: ["seed=42", "dataset.partition.strategy=iid", "wandb.run-name=iid-v2"],
    }
  - {
      name: iid_oort_boolq_s42,
      bases: [pools/50, datasets/boolq, strategies/oort, strategies/oort_50],
      overrides: ["seed=42", "dataset.partition.strategy=iid", "wandb.run-name=iid-v2"],
    }
