strategy: fedcs
task: mnli
overrides:
  - "task-name=text_classification"
  - "dataset.name=mnli"
  - "num-clients=300"
  - "device-profile-path=device_profiles/300/default/profiles.json"
  - "strategy.name=fedcs"
  - "strategy.fedcs.round-deadline-s=750.0"
  - "strategy.fedcs.c-fraction=0.5"
  - "dataset.partition.strategy=dirichlet"
  - "dataset.partition.dirichlet.alpha=8"
