strategy: random
task: mnli
overrides:
  - "task-name=text_classification"
  - "dataset.name=mnli"
  - "num-clients=300"
  - "device-profile-path=device_profiles/300/default/profiles.json"
  - "strategy.name=random"
  - "strategy.num-to-select=30"
  - "dataset.partition.strategy=dirichlet"
  - "dataset.partition.dirichlet.alpha=8"
