strategy: random
task: boolq
overrides:
  - "task-name=text_classification"
  - "dataset.name=boolq"
  - "num-clients=50"
  - "device-profile-path=device_profiles/50/default/profiles.json"
  - "strategy.name=random"
  - "strategy.num-to-select=5"
  - "dataset.partition.strategy=dirichlet"
  - "dataset.partition.dirichlet.alpha=8"
