strategy: tifl
task: boolq
overrides:
  - "task-name=text_classification"
  - "dataset.name=boolq"
  - "num-clients=50"
  - "device-profile-path=device_profiles/50/default/profiles.json"
  - "strategy.name=tifl"
  - "strategy.num-to-select=5"
  - "strategy.tifl.num-tiers=5"
  - "strategy.tifl.sync-rounds=2"
  - "strategy.tifl.prob-update-interval=5"
  - "strategy.tifl.round-deadline-s=360.0"
  - "dataset.partition.strategy=dirichlet"
  - "dataset.partition.dirichlet.alpha=8"
